#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=datn;encrypt=true;trustservercertificate=true
#spring.datasource.username=root
#spring.datasource.password=123456789
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB

spring:
  http:
    encoding: UTF-8
    charset: UTF-8
    enabled: true

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/duantn
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
custom-config:
  security:
    jwtSecret: jf9i4jgu83nfl0jfu57ejf7shdvffhdsvfsdvdshfhsdfvsdhfjf9i4jgu83nfl0jfu57ejf7shdvffhdsvfsdvdshfhsdfvsdhf
    jwtExpiration: 604800000

    endpointAuthorizations:
      - { urlPattern: "/product", method: "POST", roles: [ "ADMIN", "EMPLOYEE" ] }
      - { urlPattern: "/product/**", method: "PUT", roles: [ "ADMIN", "EMPLOYEE" ] }
      - { urlPattern: "/product/**", method: "DELETE", roles: [ "ADMIN", "EMPLOYEE" ] }

      - { urlPattern: "/image", method: "POST",roles: [ "ADMIN", "EMPLOYEE" ] }
      - { urlPattern: "/image/**", method: "PUT",roles: [ "ADMIN", "EMPLOYEE" ] }
      - { urlPattern: "/image/**", method: "DELETE",roles: [ "ADMIN", "EMPLOYEE" ] }

      - { urlPattern: "/selloff/calculate-money/**", method: "POST",roles: [ "ADMIN", "EMPLOYEE" ] }
      - { urlPattern: "/customer/fast/**", method: "POST",roles: [ "ADMIN", "EMPLOYEE" ] }

    unprotectedEndpoints:
      - { urlPattern: "/api/auth/login" }
      - { urlPattern: "/api/auth/register", method: "POST" }

      - { urlPattern: "/selloff/**", method: "POST" }

      - { urlPattern: "/product/**" }
      - { urlPattern: "/product/**", method: "GET" }

      - { urlPattern: "/bill/**" }
      - { urlPattern: "/bill/**", method: "GET" }
      - { urlPattern: "/bill", method: "POST" }
      - { urlPattern: "/bill/**", method: "PUT" }
      - { urlPattern: "/bill/**", method: "DELETE" }

      - { urlPattern: "/bill-detail/**" }
      - { urlPattern: "/bill-detail/**", method: "GET" }
      - { urlPattern: "/bill-detail", method: "POST" }
      - { urlPattern: "/bill-detail/**", method: "PUT" }
      - { urlPattern: "/bill-detail/**", method: "DELETE" }

      - { urlPattern: "/brand/**" }
      - { urlPattern: "/brand/**", method: "GET" }
      - { urlPattern: "/brand", method: "POST" }
      - { urlPattern: "/brand/**", method: "PUT" }
      - { urlPattern: "/brand/**", method: "DELETE" }


      - { urlPattern: "/address/**" }
      - { urlPattern: "/address/**", method: "GET" }
      - { urlPattern: "/address", method: "POST" }
      - { urlPattern: "/address/**", method: "PUT" }
      - { urlPattern: "/address/**", method: "DELETE" }

      - { urlPattern: "/cart/**" }
      - { urlPattern: "/cart/**", method: "GET" }
      - { urlPattern: "/cart", method: "POST" }
      - { urlPattern: "/cart/**", method: "PUT" }
      - { urlPattern: "/cart/**", method: "DELETE" }

      - { urlPattern: "/cart-detail/**" }
      - { urlPattern: "/cart-detail/**", method: "GET" }
      - { urlPattern: "/cart-detail", method: "POST" }
      - { urlPattern: "/cart-detail/**", method: "PUT" }
      - { urlPattern: "/cart-detail/**", method: "DELETE" }

      - { urlPattern: "/category/**" }
      - { urlPattern: "/category/**", method: "GET" }
      - { urlPattern: "/category", method: "POST" }
      - { urlPattern: "/category/**", method: "PUT" }
      - { urlPattern: "/category/**", method: "DELETE" }

      - { urlPattern: "/color/**" }
      - { urlPattern: "/color/**", method: "GET" }
      - { urlPattern: "/color", method: "POST" }
      - { urlPattern: "/color/**", method: "PUT" }
      - { urlPattern: "/color/**", method: "DELETE" }

      - { urlPattern: "/customer/**" }
      - { urlPattern: "/customer/**", method: "GET" }
      - { urlPattern: "/customer", method: "POST" }
      - { urlPattern: "/customer/**", method: "PUT" }
      - { urlPattern: "/customer/**", method: "DELETE" }

      - { urlPattern: "/employee/**" }
      - { urlPattern: "/employee/**", method: "GET" }
      - { urlPattern: "/employee", method: "POST" }
      - { urlPattern: "/employee/**", method: "PUT" }
      - { urlPattern: "/employee/**", method: "DELETE" }

      - { urlPattern: "/image/**" }
      - { urlPattern: "/image/**", method: "GET" }


      - { urlPattern: "/material/**" }
      - { urlPattern: "/material/**", method: "GET" }
      - { urlPattern: "/material", method: "POST" }
      - { urlPattern: "/material/**", method: "PUT" }
      - { urlPattern: "/material/**", method: "DELETE" }

      - { urlPattern: "/product-detail/**" }
      - { urlPattern: "/product-detail/**", method: "GET" }
      - { urlPattern: "/product-detail", method: "POST" }
      - { urlPattern: "/product-detail/**", method: "PUT" }
      - { urlPattern: "/product-detail/**", method: "DELETE" }

      - { urlPattern: "/size/**" }
      - { urlPattern: "/size/**", method: "GET" }
      - { urlPattern: "/size", method: "POST" }
      - { urlPattern: "/size/**", method: "PUT" }
      - { urlPattern: "/size/**", method: "DELETE" }

      - { urlPattern: "/waistband/**" }
      - { urlPattern: "/waistband/**", method: "GET" }
      - { urlPattern: "/waistband", method: "POST" }
      - { urlPattern: "/waistband/**", method: "PUT" }
      - { urlPattern: "/waistband/**", method: "DELETE" }
server:
  port: 8080




